### ISSUE TITLE
Remove 'sandbox' flight docs

### ISSUE THREAD

**Issue by adamgreig** [ukhas/habitat#104]
all docs should have timestamp start and ends

**Comment by adamgreig** [comment]
really? what was the outcome of the discussion on this? we still want to have test docs, and the easiest way to implement that is probably still a 'test' end timestamp

**Comment by danielrichman** [comment]
I can't remember exactly. I think my motivation for suggesting that all docs have some sort of end time is that it makes garbage collection easier, and forces us to keep the database relatively tidy/stops tonnes of test docs building up. (see #105)

**Comment by danielrichman** [comment]
Issue #84 depends on this one, since dl-fldigi needs to know how to work out if a doc is testing or not.

**Comment by danielrichman** [comment]
Closed by 5460517
