### ISSUE TITLE
Some kind of unit testing for CouchDB validation functions

### ISSUE THREAD

**Issue by adamgreig** [ukhas/habitat#160]
It'd be nice to have some automated testing for the validation functions.

It might be possible to make a new (temporary) Couch database, upload the design docs, then submit a bunch of known-not-allowed and known-allowed documents and check they are appropriately not allowed and allowed. Additionally some fiddling with users to check that admins and approvers can do what they should be able to, et cetera, would be good.

This might be handy for views as well, come to think of it, but probably less important.

**Comment by danielrichman** [comment]
Closed by 5460517
