### ISSUE TITLE
proposed breaking change: use ISO8601 timestamps in Couch

### ISSUE THREAD

**Issue by adamgreig** [ukhas/habitat#162]
Currently we use UNIX timestamp integers in our Couch documents. This is a basically crap format that is a pain to read or change and serves absolutely no benefit for us. I don't think it was really considered at the time...

I propose we use ISO8601 timestamps, which incidentally are the same recommended by JSON Schema for JSON documents (and almost everything else for almost everything else), and look like:

```
YYYY-MM-DDThh:mm:ssZ
```

They're easier to change, happily stored as strings, readily typed in by hand if required, can store timezone information if required, are easily validated using JSON schema, valid for untold millennia, and also

![](http://i.chzbgr.com/completestore/2012/2/14/607a288f-515e-4fee-acdd-0890ec068972.jpg)

**Comment by adamgreig** [comment]
food for thought: this generally sorts correctly and is a standard for a number of reasons, but
1. **in keys emitted in couch views it's longer and non-integer so may be slower and/or take more disk space**
2. the way it supports time offsets is generally good however it means that values are sorted by local time not by absolute time (the time written is local, the offset tells what local time is in relation to UTC)
3. which might mean things start sorting in non sensical orders
4. we could require that all times are stored as UTC
5. but then we lose out on being able to represent timezones in any way/shape/form
6. timezones are hard! currently we also totally ignore the problem by using UTC timestamps

**Comment by danielrichman** [comment]
I was going to mention the sorting-non-UTC thing but you've noticed. It's not the end of the world but I guess we would still like to support other timezones... and having two keys, one with the time and the other with the tz to display it in would suck when the first thing supports timezones. How about just having all views emit -and therefore sort by- timestamps instead of strings? I guess this makes using the row key vs an include_docs inconsistent, though...

The other solution is to patch futon. :-P

Re updating all the things: we could do it as a 0.3 thing, since all the daemons and the views would also need changing. Easy enough.

**Comment by adamgreig** [comment]
it would be nice if there was a standard format where we have a happy string like the above, but it always contains UTC, with the timezone indicating offset to obtain local time. We could actually just do that by co-opting the ISO8601 format but then I'd feel really really, really dirty...

Storing ISO8601 and then emitting UNIX timestamps in views sounds like it might be a best-of-both-worlds thing?

**Comment by adamgreig** [comment]
https://tools.ietf.org/html/rfc3339 might be a similar idea and is essentially a subset designed specifically for the internet...

**Comment by adamgreig** [comment]
https://github.com/tonyg/python-rfc3339 would work as a parser, and if views are in python they can then really easily emit UTC timestamps? generating them in python is datetime.isoformat()

parsing in Javascript is dead easy: Date.parse("1996-12-20T00:39:57Z") works correctly, outputs a millisecond timestamp in UTC, even when timezones are given in the string.

http://webcloud.se/log/JavaScript-and-ISO-8601/ has more info but it looks like generating these dates with javascript is less easy

**Comment by adamgreig** [comment]
so then: documents store RFC3339 in local time with UTC offset, and views emit UNIX timestamps in UTC.
