### ISSUE TITLE
jsonschema does not validate format specifiers

### ISSUE THREAD

**Issue by adamgreig** [ukhas/habitat#163]
jsonschema ignores format specifiers which is how "date-time" is specified for our date/time fields. this means it will check they are a string, but not that they are a well-formed RFC3339/ISO8601 string.

we could a) try to write the patch for jsonschema to at least support date-time strings b) add our own validation on top to check for this.

http://pypi.python.org/pypi/jsonschema

**Comment by adamgreig** [comment]
https://github.com/onyxfish/jsonschema is an alternative library that looks like it might support format; https://github.com/Julian/jsonschema is the library we currently use on github

**Comment by adamgreig** [comment]
looks like the first one doesn't support format either, yet.

**Comment by danielrichman** [comment]
I wouldn't be so sure; from onyxfish's::

``` python
  def validate_format(self, x, fieldname, schema, format=None):
    '''
    Validates that the value of the field matches the predifined format
    specified.
    '''
    # No definitions are currently defined for formats
    return x
```

**Comment by danielrichman** [comment]
Format support looks pretty easy to add to either of those things. I think this would be better than having 2 validate functions
