### ISSUE TITLE
listener_telemetry docs contain time as an object

### ISSUE THREAD

**Issue by adamgreig** [ukhas/habitat#169]
but perhaps it should be a more useful timestamp? I believe it's like this because of similarity to payload_telemetry: is that also a good idea? would a useful timestamp be nicer as a parser output there?

**Comment by danielrichman** [comment]
I think listener-telemetry docs should certainly have time as iso8601. payload_telemetry is slightly more difficult, since the parser has to guess the day, which might not always be possible? It could just save as a string; hh:mm:ss, which is neater than an object, really.

**Comment by adamgreig** [comment]
they already have time_uploaded and time_created -- should we
1. rename it to `time`, use it for the time associated with this position, replacing the `time` field
2. keep it as `time_created`, use it for the time associated with this position, removing the `time`
3. keep it as `time_created` used for when the telemetry document was made, use the `time` field for the time associated with the position

?

**Comment by danielrichman** [comment]
My vote is for option 2. keeping "time_created" and "time_uploaded" would be consistent with other document types, and having two keys that state the same thing is a little silly

**Comment by adamgreig** [comment]
agreed. my designdocs branch will reflect the change and I'll update the docs accordingly, but we'll need to take this into account when we update the existing database to use the rfc3339 dates
