### ISSUE TITLE
CouchDB View for Listener Telemetry by Callsign

### ISSUE THREAD

**Issue by priyeshpatel** [ukhas/habitat#178]
A CouchDB view to Listener Telemetry documents by callsign (sorted by timestamp)

e.g. the key could be [callsign, timestamp] just like Payload Telemetry

**Comment by adamgreig** [comment]
I've got this in the new python based view functions, for listener telemetry and listener info, so you should see it once we transition to them.

**Comment by danielrichman** [comment]
Closed by 5460517
