### ISSUE TITLE
Habitat filter to round values

### ISSUE THREAD

**Issue by priyeshpatel** [ukhas/habitat#179]
A numeric scale filter can result in lots of decimal places, so some way of limiting and rounding the number would be useful

**Comment by danielrichman** [comment]
A filter to round to a certain precision is not only a good idea, it's easy to add...

Also, sources of ridiculous decimal places include:
- dividing by 60 in ddmm -> dd.dd. We could modify the filter to round (or not?)
- common filters numeric scale - we could teach it to automatically round to the number of significant figures in the input, or we could add rounding as a config thing, to save an extra filter (would be a little kludgy to have filters on everything)
- floats. Ugh. Look at this from osiris: Battery: 6.0120000000000005 V. The filter is divide by 1000. :-(

Could have spacenearus round it; i.e., leave it all up to the ui. But rounding has other benefits like reducing size of the json data, which is cool.

My vote is for rounding on default in numeric scale and ddmm->dddd, but with a config option to override (disable, or change s.f.)

**Comment by priyeshpatel** [comment]
I'd go with the second option:
- a config parameter for rounding to a certain number of decimal places or significant figures
- if no config parameter has been passed, round to the number of significant figures in the input

**Comment by priyeshpatel** [comment]
Fixed with pull request #180
