### ISSUE TITLE
transition the database

### ISSUE THREAD

**Issue by adamgreig** [ukhas/habitat#192]
from pre- to post-transition: mostly we want to move config and flight docs, and then package up existing flight data into archive files.

**Comment by danielrichman** [comment]
We only need to transition payload_configuration docs; we can backup/rename the habitat database, and then (manually) export the data inside when we add the archive daemon.

**Comment by danielrichman** [comment]
This is done and ready to be loaded into a live database. https://gist.github.com/3472776

**Comment by danielrichman** [comment]
Loaded into http://beta.habitat.habhub.org/
