### ISSUE TITLE
consider checking sanity of dates (or maybe ranges) in validation

### ISSUE THREAD

**Issue by danielrichman** [ukhas/habitat#199]
e.g., within 1 week of now, or not in the past, etc.

**Comment by adamgreig** [comment]
what're the advantages? we use system time to determine flights to search for, and we exclude outliers from received time calculations, so in theory this doesn't gain us much but does potentially mean losing/not-accepting data from someone with a misconfigured local clock.

But, I'm pretty sure I'm missing something.

**Comment by danielrichman** [comment]
I was thinking for flight docs: we restrict the range of the flight window to a week; but don't check the value of launch date isn't something silly. However, that's not really an issue because of approval, I guess.

"potentially mean losing/not-accepting data from someone with a misconfigured local clock" - you're right, the benefits aren't really that great; and thinking about it the planned archiver might ignore anything that falls out of the range of the flight anyway
