### ISSUE TITLE
Flight documents with the same start and end date get mixed together

### ISSUE THREAD

**Issue by adamgreig** [ukhas/habitat#253]
If two flight documents with different payloads but the same start and end date exist, then the `flight/end_start_including_payloads` view gives them the same key and sorts them, leaving the two flight docs first (with identical keys ending in 0) and then the two payloads (with identical keys ending in 1). This makes dl-fldigi (and etc) think the last flight doc has two payloads instead of one per document.

Suggested fix: add another field to the key before the 0/1 at the end that is something like the flight document ID, or a part of it, or the flight name, or something similar. This will prevent duplicate keys and so ensure sorting works correctly.

**Comment by danielrichman** [comment]
I believe (off the top of my head) that CouchDB sorts by doc id, then order
emitted if keys are identical. So we could instead simply remove the
is_pcfg key / the third item in the key (I... think?) and it will sort correctly.
OTOH Explicit is better and the view is small so space isn't really an
issue, making what you suggested better.
Of course the hardest bit is not fixing the bug but updating dl-fldigi.
Perhaps we should hold off fixing this incase any other bugs show up, then
kill them all in one go.

**Comment by danielrichman** [comment]
The fixes to dl-fldigi, calendar, habitat, (maybe some others) are ready to be deployed.
