### ISSUE TITLE
Validation rejects uploads with 'only the parser may modify data' because floats.

### ISSUE THREAD

**Issue by danielrichman** [ukhas/habitat#270]
F***ing floats.

'longitude': 1.1065502999999999 vs 'longitude': 1.1065503

Note: currently these files are hotpatched (the former will need clearing up since it's not in git)

~habitat/venv/lib/python2.7/site-packages/couch_named_python/pyviews.py
- added logging of the arguments when validation fails + an import json.

~habitat/habitat/habitat/views/payload_telemetry.py
- shallow loop rounds all floats to 7dp before 'if new['data'] == old['data']'

``` python
diff --git a/habitat/views/payload_telemetry.py b/habitat/views/payload_telemetry.py
index fd9cee9..cbc63cf 100644
--- a/habitat/views/payload_telemetry.py
+++ b/habitat/views/payload_telemetry.py
@@ -72,6 +72,14 @@ def validate(new, old, userctx, secobj):
         raise ForbiddenError("Document ID must be sha256(base64 _raw data)")

     if old:
+        for key in old["data"]:
+            if key not in new["data"]:
+                continue
+            if isinstance(old["data"][key], float) or \
+                    isinstance(new["data"][key], float):
+                for hack in [old["data"], new["data"]]:
+                    hack[key] = int(round(hack[key] * 1e7))
+
         if new['data'] != old['data'] and 'parser' not in userctx['roles']:
             raise UnauthorizedError("Only the parser may add data to an"
                                     " existing document.")
```

**Comment by adamgreig** [comment]
Ughgh. Rounding before comparing is one option. Might be better off checking that the difference between the two values is less than some epsilon (which is quite small) rather than just rounding the floats as I'm not sure that will always help prevent the issue?

**Comment by danielrichman** [comment]
I believe the best way to do it is to set the epsilon based on the size of the largest float, though that may be unnecessarily complicating things. Rounding was indeed a quick hack. Some nice recursive deep comparey function would be better
