### ISSUE TITLE
Lots and lots of conflicts when putting payload telemetry

### ISSUE THREAD

**Issue by danielrichman** [ukhas/habitat#271]
I picked a random upload. For 30 listeners to upload the same string, there were ~200 conflicts. This isn't really very efficient.

Idea: random sleep before conflict merge
Sleep would have to be before the GET step to achieve anything.

**Comment by adamgreig** [comment]
Sounds reasonable and doesn't have to be long. Could exponential falloff when retrying but that will be problematic if everyone falls off by the same amount. Possibly a random sleep plus some exponential factor.... that could be overcomplicated.

Perhaps just the random sleep.

**Comment by danielrichman** [comment]
Used an update function. This mitigates the problem although doesn't solve it entirely.

Before, a randomly sampled doc save took 223 conflicts and 11 seconds in total. My test python script using the previous version of the habitat uploader takes about 6 seconds (running on my machine) and a comparable number of conflicts. Using the update function instead/ takes 1.8 seconds and 165 conflicts.

(The above does not constitute an actual evaluation of how bad the problem is/to what extent it has been fixed)
