### ISSUE TITLE
Add speed to listener_telemetry

### ISSUE THREAD

**Issue by priyeshpatel** [ukhas/habitat#283]
Speed should be added to the listener_telemetry schema as an optional field so that the field name and units can be standardised (perhaps to m/s?).

Currently, spacenear.us displays speed as km/h so if it were changed to m/s, the spacenear.us uploader would have to do the conversion.

**Comment by priyeshpatel** [comment]
Android app will get a fix soon(ish): https://github.com/priyeshpatel/habhub-chase-car-tracker/issues/17

**Comment by priyeshpatel** [comment]
https://github.com/ukhas/habitat/pull/284

**Comment by danielrichman** [comment]
TODO: Convert old android app documents (data.client.application_version <= 0.1.6) to be m/s (from km/h)
