### ISSUE TITLE
payload_telemetry view, keys [estimated_time_received]

### ISSUE THREAD

**Issue by danielrichman** [ukhas/habitat#287]
By popular request, to make iOS/Android map viewers.

Pro
- simple to use
- people asked for it

Con
- encourages a bodge
- no concern for testing/live. Maybe could have two views to account for this
- no real way to load data when the app is first opened.

Admittedly, until we come up with a decent way to sync changes to a view (_view_changes couch modification maybe? IDK) anything that attempts to load and sync flight telemetry is going to be a bit of a bodge.

**Comment by adamgreig** [comment]
Hum. This is definitely an easy way to implement a quick map view of recently uploaded telemetry and is probably fine for just that use case. It's obviously less good for implementing some of "proper" map but hopefully those people could use the stream+filter.

As a view into the data it seems like a good idea. We can document specifically what we advise it's used for which might discourage too bad bodging -- but it's still going to be better than say querying spacenear.us or parsing logtail (which have both happened!).

Testing/live is a legit concern. Could emit a 0/1 in the key for that, or indeed two views.

Easy enough to load data when first opened by just requesting data at some point into the past, or with a limit statement to get the last n telemetries. Loading an entire flight is harder but could be done: load the last half hour / last 100 data points, then for all the flights you see data from the user could select one to load its entire data via the existing views.

**Comment by danielrichman** [comment]
Testing-live: I think?? people using this view will either want "live" or "testing and live / everything"; rather than one or the other. So, we could have two views, or the key could be [testing, time] with live documents emitted twice, once in testing and once in live.

Or we could try and satisfy all three cases with 3 views, or a 0/1/2 parameter... I'm not sure.

However, if we can resolve that then I'm happy to try and throw this together tomorrow for cuddykid
