### ISSUE TITLE
Parser should catch CouchDB validation errors and return them as parse errors

### ISSUE THREAD

**Issue by adamgreig** [ukhas/habitat#291]
Right now if CouchDB fails a newly parsed document due to validation (which may occur for example when the payload document says that a certain field is an integer but the schema says that field name should be a string), the exception goes all the way to the top and generates an error email to the devs.

Much better would be for the parser to check for validation errors while saving and if encountered, report them as parse errors (so they appear in the normal log) and then not crash.

**Comment by danielrichman** [comment]
Closed by 4d4cf2c / #301 - (#299 and #291 mistakenly swapped)
