### ISSUE TITLE
With a lot of receivers only a small part of uploaded packets seems to be stored

### ISSUE THREAD

**Issue by zanco** [ukhas/habitat#324]
Today I received 633 LoRa packets on 434.450 from Daveake's flight. Only 78 (edit type error) are logged in the Pi chart for PE2BZ. I spoke to Ron g8fjg and he noticed  (I quote)
"my image 44 only has a few blocks missing but the one on ssdv live has big chunks missing " so it looks like his received 868 MHz image packet also missed a lot of uploads.

One strang thing, that might add to the solution, PE1ANS was using the Windows tracker from Daveake with the LoRa module and all his packets where logged in the Pi chart.  (at least he used this tracker last weekend end as far as I know he has no PiTS board)

Is this the right location for this issue ? Thanks in advance,
Ben - PE2BZ

**Comment by richardeoin** [comment]
Unfortunately this is a downside of CouchDB. If a document merge is already in progress when your uploaded packet arrives, your packet will be rejected (I think with 409 Conflict). This [already documented](https://github.com/ukhas/habitat/blob/develop/habitat/views/payload_telemetry.py#L258), and CouchDB behaves in this way so it can be used as a distributed database if required (it isn't for habitat).

As the docs say, if you receive a Conflict you should retry. For instance, dl-fldigi [does this](https://github.com/ukhas/habitat-cpp-connector/blob/master/src/Uploader.cxx#L148).

**Comment by danielrichman** [comment]
On 17 Aug 2016 11:10 p.m., "Richard Meadows" notifications@github.com
wrote:

> Unfortunately this is a downside of CouchDB. If a document merge is
> already in progress when your uploaded packet arrives, your packet will be
> rejected (I think with 409 Conflict). This already documented, and CouchDB
> behaves in this way so it can be used as a distributed database if required
> (it isn't for habitat).
> 
> As the docs say, if you receive a Conflict you should retry. For
> instance, dl-fldigi does this.

Indeed, the habitat python client does it too:
https://github.com/ukhas/habitat/blob/develop/habitat/uploader.py#L219

**Comment by zanco** [comment]
Thanks for the explanations. Indeed the windows tracker uses the python client. M0RJX is trying to take care of the LoRa part for repeating messages after being rejected I noticed.
Topic can be closed, big thanks for the great support !
