### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by kaklik** [ukhas/habitat#325]
Hello, 

I want to use Habitat library to push our telemetry data to your map. But I have a problem with the installation of the library. 
I proceed these steps: 

    git clone https://github.com/ukhas/habitat.git
    cd habitat/
    pip install -r requirements.txt

But for now I am now hanged on following error: 

~/programy/habitat$ sudo python setup.py build
sudo: unable to resolve host kaklik-ultrabook
/usr/lib/python2.7/dist-packages/setuptools/dist.py:285: UserWarning: Normalizing '0.2dev' to '0.2.dev0'
  normalized_version,
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/habitat
copying habitat/loadable_manager.py -> build/lib.linux-x86_64-2.7/habitat
copying habitat/uploader.py -> build/lib.linux-x86_64-2.7/habitat
copying habitat/filters.py -> build/lib.linux-x86_64-2.7/habitat
copying habitat/__init__.py -> build/lib.linux-x86_64-2.7/habitat
copying habitat/parser_daemon.py -> build/lib.linux-x86_64-2.7/habitat
copying habitat/parser.py -> build/lib.linux-x86_64-2.7/habitat
creating build/lib.linux-x86_64-2.7/habitat/parser_modules
copying habitat/parser_modules/ukhas_parser.py -> build/lib.linux-x86_64-2.7/habitat/parser_modules
copying habitat/parser_modules/__init__.py -> build/lib.linux-x86_64-2.7/habitat/parser_modules
copying habitat/parser_modules/simple_binary_parser.py -> build/lib.linux-x86_64-2.7/habitat/parser_modules
creating build/lib.linux-x86_64-2.7/habitat/sensors
copying habitat/sensors/stdtelem.py -> build/lib.linux-x86_64-2.7/habitat/sensors
copying habitat/sensors/__init__.py -> build/lib.linux-x86_64-2.7/habitat/sensors
copying habitat/sensors/base.py -> build/lib.linux-x86_64-2.7/habitat/sensors
creating build/lib.linux-x86_64-2.7/habitat/utils
copying habitat/utils/checksums.py -> build/lib.linux-x86_64-2.7/habitat/utils
copying habitat/utils/filtertools.py -> build/lib.linux-x86_64-2.7/habitat/utils
copying habitat/utils/__init__.py -> build/lib.linux-x86_64-2.7/habitat/utils
copying habitat/utils/immortal_changes.py -> build/lib.linux-x86_64-2.7/habitat/utils
copying habitat/utils/quick_traceback.py -> build/lib.linux-x86_64-2.7/habitat/utils
copying habitat/utils/dynamicloader.py -> build/lib.linux-x86_64-2.7/habitat/utils
copying habitat/utils/startup.py -> build/lib.linux-x86_64-2.7/habitat/utils
running build_scripts
creating build/scripts-2.7
error: file './programy/habitat/bin/habitat' does not exist

**Comment by rossengeorgiev** [comment]
You don't need to install habitat to push data. There a RESP API for that.

Here is an example in python: https://github.com/rossengeorgiev/hab-tools/blob/master/send_tlm_to_habitat.py

You can find the schema at http://habitat.habhub.org/jse/

**Comment by kaklik** [comment]
Thank you for a fast response, but it is somehow unclear for me what format the  "sentence" argument should have. 
Do you think that I do not need to install https://github.com/ukhas/habitat.git for anything?

**Comment by rossengeorgiev** [comment]
The sentence format is whatever you configured in your payload doc

> Do you think that I do not need to install https://github.com/ukhas/habitat.git for anything?

No, unless you want to run your own server and habitat is just one component.
